# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Letisia's Technology Portfolio"
title_separator: "|"
subtitle: "Cloud Solutions • Innovation • Technology Leadership"
email: contact@letisiapangataa.com
description: "Technology portfolio showcasing cloud architecture, innovation, and leadership in the digital transformation space. Follow my journey from Microsoft to new frontiers in tech."
url: "https://letisiapangataa.github.io"
baseurl: ""
repository: "letisiapangataa/letisiapangataa.github.io"
masthead_title: "Letisia's Technology Portfolio"
twitter_username: letisiapangataa
github_username: letisiapangataa
linkedin_username: letisiapangataa
minimal_mistakes_skin: "dark"
search: true
search_full_content: true
search_provider: lunr
lunr:
  search_within_pages: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

author:
  name   : "Letisia Pangata'a"
  avatar : "https://res.cloudinary.com/louiy9obu/image/upload/v1628419918/B84D1E9F-0C77-4FE3-9AEE-A7EAC0BCB8D9_evlxba.jpg"
  bio    : "Cloud Solution Architect • Technology Leader • Innovation Catalyst<br/>Bridging business needs with cutting-edge cloud solutions"
  location: "Auckland, New Zealand 🇳🇿"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:contact@letisiapangataa.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/letisiapangataa"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/letisiapangataa/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/letisiapangataa"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/letisiapangataa"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/letisiapangataa/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/letisiapangataa"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:contact@letisiapangataa.com"


teaser: /assets/images/500x300.png


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      classes: wide
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

# SEO Related
google_site_verification: 
bing_site_verification:
yandex_site_verification:
naver_site_verification:

# Social Sharing
twitter:
  username: "letisiapangataa"
facebook:
  username: 
  app_id:
  publisher:
og_image: "https://res.cloudinary.com/louiy9obu/image/upload/v1626002590/letisias_projects_fjlv67.png"

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: 
    anonymize_ip: false

# Comments
comments:
  provider: "disqus"
  disqus:
    shortname: "letisia-tech-portfolio"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
